---
- hosts: dil_uat_fortimanager
  connection: httpapi
  collections:
  - community.general
  tasks:
   - name: Ansible input vars example
     community.general.terraform:
       project_path: "/var/lib/awx/terraform/fortimanager"
       state: '{{ state }}'
       variables:
         objname: terraform
       force_init: true