---
- hosts: dil_uat_fortimanager
  connection: httpapi
  collections:
  - community.general
  tasks:
#   - name: Basic deploy of a service
#     community.general.terraform:
#       project_path: "/var/lib/awx/terraform/fortimanager"
#       state: '{{ state }}'
#   - name: Define the backend configuration with one or more files at init
#     community.general.terraform:
#       project_path: '{{ project_dir }}'
#       state: present
#       force_init: true
#       backend_config_files:
#         - /path/to/backend_config_file_1
#         - /path/to/backend_config_file_2
   - name: Complex variables example
     community.general.terraform:
       project_path: "/var/lib/awx/terraform/fortimanager"
       state: '{{ state }}'
       complex_vars: false
       variables:
         objname: "test12345"
       force_init: true
#       
#   - name: Complex variables example
#     community.general.terraform:
#       project_path: "/var/lib/awx/terraform/fortimanager"
#       state: '{{ state }}'
#       complex_vars: true
#       variables:
#         vm_name: "{{ inventory_hostname }}"
#         vm_vcpus: 2
#         vm_mem: 2048
#         vm_additional_disks:
#           - label: "Third Disk"
#             size: 40
#             thin_provisioned: true
#             unit_number: 2
#           - label: "Fourth Disk"
#             size: 22
#             thin_provisioned: true
#             unit_number: 3
#       force_init: true