---
- hosts: dil_uat_fortimanager
  connection: httpapi
  collections:
  - community.general

  tasks:
   - name: Ansible input vars example
     community.general.terraform:
       project_path: "/var/lib/awx/terraform/fortimanager"
       state: '{{ state }}'
       variables:
         objname: terraform
         ansible_user: '{{ ansible_user }}'
         ansible_password: '{{ ansible_password }}'
       force_init: true