---
- hosts: dil_uat_fortimanager
  connection: httpapi
  collections:
  - community.general
  tasks:
   - name: Basic deploy of a service
     community.general.terraform:
       project_path: "tmp/terraform/"
       state: present