---
- hosts: dil_uat_fortimanager
  connection: httpapi
  collections:
  - community.general
  tasks:
   - name: Basic deploy of a service
     community.general.terraform:
       project_path: '{{ project_dir }}'
       state: present
#   - name: Define the backend configuration with one or more files at init
#     community.general.terraform:
#       project_path: '{{ project_dir }}'
#       state: present
#       force_init: true
#       backend_config_files:
#         - /path/to/backend_config_file_1
#         - /path/to/backend_config_file_2       